image: Ubuntu1804  # образ для сборки

stack: node 10  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

environment:
  access_token:
    secure: zYCOwcOlgTzvbD0CjJRDNQ==

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name Lazy-ferret
  - git config --global user.email a.veselov83@gmail.com
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
